### PR TITLE
Toon Kingdom fix

### PR DESCRIPTION
**Pull request by destdev**
fixes issue where Toon Monsters are still able to be targeted by stuff
like fiendish chain or magic cylinder

### CODE REVIEW

**Comment by salix5** [comment]
Can you upload the replay file?
Thank you.

**Comment by destdev** [comment]
you can find the replay here:
http://forum.ygopro.de/index.php/Thread/11720-Toon-Kingdom-currently-not-protecting-against-targeting/
turn 5 shows, that fiendish is able to target the cowboy taken by comic hand (though it doesn't negate the effect and shows an Error for the fiendish chain script, most propably because of the conflict), turn 7 toon dark magician girl attacks and is able to be targeted by magic cylinder

**Comment by salix5** [comment]
https://github.com/salix5/CardEditor/blob/master/ygopro0.exe
This is the file based on f2b0c
It shows an error in turn 4.

**Comment by destdev** [comment]
hu ... strange thing ...
I was able to reproduce that bug perfectly fine 2 days ago, now I can't anymore ...
I must have missed something, not sure what exactly ... propably a missed update of some sort
sorry for the inconvenience

**Pull request closed without merging**
