### PR TITLE
update pos of ShowCardInfoInList, fix the tip blink

### PR DESCRIPTION
**Pull request by mercury233**
image
image
image

### CODE REVIEW

**Comment by purerosefallen** [comment]
I don't think there are super long cards names, at least in OCG/TCG.

**Comment by mercury233** [comment]
image

**Comment by purerosefallen** [comment]
image
why not expanding the tip size here?

**Comment by mercury233** [comment]
image
it cant go beyond the window

**Comment by edo9300** [comment]
Wouldn't putting the tip object outside the card select solve that?

**Comment by mercury233** [comment]
@edo9300 it will be a bit ugly imo... 
image
image

**Pull request merged**
