### PR TITLE
Search cards with RegEx

### PR DESCRIPTION
**Pull request by purerosefallen**
Now you can use any RegEx in card search. Cards matching given RegEx will be at the first.

### CODE REVIEW

**Comment by edo9300** [comment]
@purerosefallen please, remove that doubled definition that's basically the same stuff (it's weird that the compiler didn't detect it as ambiguous) also take the strings by reference as const values

**Comment by purerosefallen** [comment]
where's the double definition?

**Comment by DailyShana** [comment]
I dont think there is any necessity so support regex. It's too professional for general users.

**Comment by cpcolella** [comment]
on the flip side, not including RegEx is too basic for advanced users.

**Comment by NewScript** [comment]
E pelo lado que estão esquecendo, usar regex vai adicionar alguma experiência para o usuário?

**Pull request closed without merging**
