### PR TITLE
Puzzle message support (reading from lua comments)

### PR DESCRIPTION
**Pull request by edo9300**
This does the same thing as https://github.com/Fluorohydride/ygopro/pull/2135, but instead of using custom headers to define the message, it loads the message form the first comment found in the script with this scheme 
```
--[[mesage
what is actually shown
]]
```

### CODE REVIEW

**Comment by purerosefallen** [comment]
How about the 1st written in this way?
```
--[[ message
what is actually shown
]]
```
or
```
	--[[message
	what is actually shown
	]]
```
?

**Comment by purerosefallen** [comment]
In my opinion, it's fairly enough to detect whether `--[[` exists in the 1st line, and use the 1st line with `]]` for the end.

**Comment by purerosefallen** [comment]
COMPILE ERROR:
```
         drawing.cpp
         duelclient.cpp
         event_handler.cpp
         game.cpp
     2>..\gframe\game.cpp(2080): error C2079: “infile”使用未定义的 class“std::basic_ifstream<char,std::char_traits<char>>” [C
       :\ygo\ygopro\build\ygopro.vcxproj]
     2>..\gframe\game.cpp(2080): error C2440: “初始化”: 无法从“const char *”转换为“int” [C:\ygo\ygopro\build\ygopro.vcxproj]
         ..\gframe\game.cpp(2080): note: 没有使该转换得以执行的上下文
     2>..\gframe\game.cpp(2081): error C2440: “<function-style-cast>”: 无法从“int”转换为“std::istreambuf_iterator<char,std::c
       har_traits<char>>” [C:\ygo\ygopro\build\ygopro.vcxproj]
         ..\gframe\game.cpp(2081): note: 无构造函数可以接受源类型，或构造函数重载决策不明确
     2>..\gframe\game.cpp(2082): error C2664: “std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar
       _t>>::basic_string(const std::basic_string<wchar_t,std::char_traits<wchar_t>,std::allocator<wchar_t>> &)”: 无法 将参数
        1 从“std::istreambuf_iterator<char,std::char_traits<char>>”转换为“std::initializer_list<_Elem>” [C:\ygo\ygopro\buil
       d\ygopro.vcxproj]
                 with
                 [
                     _Elem=wchar_t
                 ]
         ..\gframe\game.cpp(2082): note: 没有可用于执行该转换的用户定义的转换运算符，或者无法调用该运算符
         gframe.cpp
         image_manager.cpp
```

**Comment by edo9300** [comment]
@purerosefallen apparently I forgot to put the fstream header in those modified files, you should be able to compile now

**Comment by purerosefallen** [comment]
I tested this, but not working.
Here's my single script:
```
--[[message
A script to test the redtexts in custom cards. Now this one is replaced by travis script.
]]
--Made by purerosefallen

io=require('io')
os=require('os')
os.remove("error.log")
Debug.Message(os.date())
Debug.SetAIName("Check Scripts")
Debug.ReloadFieldBegin(DUEL_ATTACK_FIRST_TURN+DUEL_SIMPLE_AI)
Debug.SetPlayerInfo(0,8000,0,0)
Debug.SetPlayerInfo(1,8000,0,0)
local f=io.popen("bash echo \"select id from datas;\" | sqlite3 expansions/222DIY.cdb")
for line in f:lines() do
	Debug.AddCard(tonumber(line),0,0,LOCATION_GRAVE,0,POS_FACEUP_ATTACK,true)
end
f:close()
Debug.ReloadFieldEnd()
```

**Comment by edo9300** [comment]
Hmm, it seems like a file encoding issue, could you send your lua scrpit? Because if i just copy paste this in a new file, it works fine

**Comment by purerosefallen** [comment]
This one is done by https://github.com/Fluorohydride/ygopro/commit/553330c7f633b043cbe269c4aafddc14fd6f17da, so closed.

**Pull request closed without merging**
