### PR TITLE
update strings.conf

### PR DESCRIPTION
**Pull request by nekrozar**
- Add Magician's japanese setname and Galaxy-Eyes Tachyon Dragon's japanese setname
- ~~Remove japanese setname ruby~~
- Fix Majestic's japanese setname and Ojama's japanese setname

### CODE REVIEW

**Comment by DailyShana** [comment]
I think in the following cases, ruby should be recorded:
1. the base of a setname appears with different ruby.
eg. 白竜の聖騎士 is not 聖騎士(せいきし) card.
2. the base is consist of one or two English letters and the ruby has actual meaning

**Comment by nekrozar** [comment]
Add ruby. (Sorry, I thought ruby doesn't need...)
I think that it is better to add English setname.

**Comment by DailyShana** [comment]
English setname should be used in English version
Japanese setnames here is only treated as reference because whether a card belong to a series depends on its Japanese name.

**Comment by nekrozar** [comment]
I understand.

**Pull request merged**
