### PR TITLE
Add resizing and skins

### PR DESCRIPTION
**Pull request by IceYGO**
Both options are entirely optional and disabled by default. You must explicitly allow the resizing in the configuration file or create the skins folder for enable them.

```
# 1 to allow the user to resize the window
allow_resize = 1
# 0 means "load the first skin in the skins folder",
#   use -1 or delete skins folder to disable
skin_index = 0
```

Here is a screenshot of the deck editor with the default skin:

deck-editor

It works with OpenGL and DirectX and supports unicode fonts.

[You can download the default skins folder here.](http://s000.tinyupload.com/index.php?file_id=01906278824443797604) (Sorry, couldn't find a better website to upload it)

### CODE REVIEW

**Comment by IceYGO** [comment]
Implements #1633

**Comment by Zayelion** [comment]
Do you have a sample binary?

**Comment by IceYGO** [comment]
[Here you go, a sample binary, config and skins folder.](http://s000.tinyupload.com/index.php?file_id=05329096036193857678)
It is only built for OpenGL, do not try do run it with Direct3D enabled in the config file.

**Comment by Zayelion** [comment]
Thank you, Im passing this on the the Salvation QA team to test, they will post back their findings.

**Comment by salix5** [comment]
@Fluorohydride 
@VanillaSalt 
不好意思 我對GUI比較不熟
可以幫忙查看一下這個項目嗎？

**Comment by DailyShana** [comment]
The resizing is ugly if the font size cannot adjust itself.

And the skin system do not support title bar:
image
image
This two window objects has no title bar, but it still draw a "title bar" is from the texture.
So all window objects look very uncomfortable:
image

**Comment by Zayelion** [comment]
ugh the code has rotted a bit and requires merges :-/

There are other themes, when I pass out Salvation it comes with this one:
https://github.com/SalvationDevelopment/Salvation-YGOPro-Theme

There is a library of themes here :
http://www.ygopro.co/Forum/tabid/95/g/posts/t/1861/YGOPro-Themes-Index#post12420

**Comment by IceYGO** [comment]
I will probably re-open two different pull requests (resizing AND skins, they are two different thing) when the time comes.

I don't think this code is ready to get merged right now because of a few problems, including what has been reported by DailyShana above and what other users reported.

**Pull request closed without merging**
