### PR TITLE
update conti_act operation mark

### PR DESCRIPTION
**Pull request by mercury233**
GIF

The conti_act operation mark may be barely noticeable on some background images, so draw the cards behind it.

### CODE REVIEW

**Comment by DailyShana** [comment]
as there is no actual card in that place, the cards should be transparent.
and the place indicates conti act should be moved to the place above field zone:
image

**Comment by mercury233** [comment]
the effect can be owned by any player, so we shouldn't make it look like only one player

**Comment by mercury233** [comment]
it will be weird if multiple cards are drawn transparent

**Comment by DailyShana** [comment]
> the effect can be owned by any player, so we shouldn't make it look like only one player

it's outside the field, so doesn't mean anything about where the effects come from

**Comment by mercury233** [comment]
nobody will think a card above the field zone is outside the field

**Comment by DailyShana** [comment]
> nobody will think a card above the field zone is outside the field

There is no frame. Contrarily, a card in the center of the field is more likely to be think as a card in the field

**Comment by DailyShana** [comment]
> it will be weird if multiple cards are drawn transparent

only draw card image of the first card, make other cards completely transparent to indicate the count

**Comment by mercury233** [comment]
image
image
image

more people prefer it in center, and it had been in center for a long time

**Pull request merged**
