### PR TITLE
add setting for drawing single chain

### PR DESCRIPTION
**Pull request by mercury233**
another solution for https://github.com/Fluorohydride/ygopro/pull/2299

### CODE REVIEW

**Comment by DailyShana** [comment]
can't agree this change, there is no problem to solve

**Comment by mercury233** [comment]
The problem is, many users, including me, think the chain 1 mark is useless and will slow down the game.

**Comment by DailyShana** [comment]
it's necessary

**Comment by mercury233** [comment]
I don't think we missed this neccessary feature for years.

**Comment by DailyShana** [comment]
but that's the fact

**Comment by purerosefallen** [comment]
Meeting all players' satisfaction could be a good idea.

**Comment by mercury233** [comment]
According to the [rulebook](https://img.yugioh-card.com/japan/howto/data/rulebook_masterrule20200401_ver1.0.pdf) page 58, "chain" should contain 2 cards, so single chain shouldn't be draw, I will change this pull request to making an option for showing chain 1 to distinguish which card is activated.

**Comment by DailyShana** [comment]
>一方玩家进行卡片或效果的发动后，该发动作为**连锁1**积累连锁。该时点优先权转移给对方玩家，对方玩家可以决定是否发动任意发动（选发）的卡或效果。之后，优先权再度转移给最初的玩家，该玩家决定是否发动效果。但是，如果是同一时点有复数诱发效果的场合，是按照决定好的优先度顺序发动。
对应**连锁1**发动卡的场合，该发动作为连锁2积累连锁。之后还有卡发动的场合，依照连锁3→连锁4这样的顺序积累连锁。
双方玩家都没有要发动的卡的场合，进行到那时为止积累的连锁的处理。
https://warsier.gitbooks.io/new_master_rule/4/42/424/4242.html

**Comment by mercury233** [comment]
chain 1 exists only if chain 2 exists

**Comment by DailyShana** [comment]
there is one chain, then it's chain 1, else chain 2 is no sense

**Comment by mercury233** [comment]
> 连锁……，是指对应一张卡的发动而发动另一张卡的行为。

**Comment by DailyShana** [comment]
>一方玩家进行卡片或效果的发动后，该发动作为连锁1积累连锁

**Comment by mercury233** [comment]
> chain 1 makes sense only if chain 2 exists

**Pull request merged**
