### PR TITLE
update command line parameters

### PR DESCRIPTION
**Pull request by mercury233**
Make ygopro can be started with more parameters.

- -e foo.cdb
Load foo.cdb as external database. Multi parameters are supported.
- -n Mercury233
Enter `Mercury233` as nickname.
- -h 127.0.0.1
Enter `127.0.0.1` to host ip textbox.
- -p 233
Enter `233` to host port textbox.
- -w 123456
Enter `123456` to host password textbox.
- -x
Exit ygopro when returning from any mode. Some launcher of ygopro is needing this.
- -j
Automatic join host. Should be used along with `-h` `-p` etc.
- -d [filename]
Automatic open deck edit mode. If `filename` is presented, the file will opened. Files with full path are supported. If the file is in correct folder of ygopro, you can use filename instead. The same below.
- -r [filename]
Automatic open replay mode and open `filename` .
- -s [filename]
Automatic open single mode and open `filename` .

`-j` `-d` `-r` `-s` must be the last parameter.

### CODE REVIEW

**Comment by DailyShana** [comment]
更新命令行参数似乎会导致一些启动器之类的兼容性问题

**Comment by mercury233** [comment]
目前据我所知第三方启动器没有一个是直接使用这里的源码进行编译的，如果他们想同步这个修改也很简单。

**Comment by DailyShana** [comment]
兼容性和修改简不简单是两码事
还有-d, -r, -s这几个参数直接使用`-d filename`这种应该更自然一些

**Comment by mercury233** [comment]
所以说不存在兼容性问题，这里的版本没有需要主动去兼容的启动器
-o我去掉了

**Comment by DailyShana** [comment]
为什么要单独分开一个-x参数
对于-j -d -r -s这几个参数，直接`exit_on_return=true`比较合理一些吧

**Comment by mercury233** [comment]
有时候会需要不退出的

**Pull request merged**
