### PR TITLE
Update c17412721.lua

### PR DESCRIPTION
**Pull request by nizhuan-jjr**
Experienced a script error:
[string "./script/c17412721.lua"]:41:attempt to index local 'tc'(a nil value)
So,I think the change would resolve such error.

### CODE REVIEW

**Comment by salix5** [comment]
Can you upload that replay file?
Thank you.

**Comment by nizhuan-jjr** [comment]
It's AI mode, so I wasn't able to save a replay, and I also forgot to do so...

**Comment by salix5** [comment]
AI mode is  the function of Percival's version.
Maybe you can go to their forum for help?

**Comment by nizhuan-jjr** [comment]
Oops,I didn't realize that.
Would you mind providing a link to the forum?

**Comment by salix5** [comment]
http://www.ygopro.co/Forum.aspx

**Pull request closed without merging**
