### PR TITLE
Fix crashes in MacOS

### PR DESCRIPTION
**Pull request by zhykzhykzhyk**
* Prevent GL method being called from other threads

### CODE REVIEW

**Comment by mercury233** [comment]
Personally I prefer not to introduce new libraries, so I wonder if it is possible to fix this in another way.

**Comment by zhykzhykzhyk** [comment]
New libraries? You mean STL?

**Comment by mercury233** [comment]
Yes, and I said it is just personally preference of mine `_(:з」∠)_`.

**Comment by zhykzhykzhyk** [comment]
Do you mean that both the queue and the type erased function need to be implemented again in this project even it is already there in the STL, or there is a technic you are trying to avoid?

**Comment by mercury233** [comment]
I mean we should use new library only if necessary.

**Comment by Zayelion** [comment]
If its in `std` isn't it already included? By don't add new libs dont you mean stuff like `irrKlang` and `sfml`?

**Comment by xiliu98** [comment]
If stl library is forbidden to use, then what stl-like library else can we use?

**Comment by zhykzhykzhyk** [comment]
Close in favor of #2025

**Pull request closed without merging**
