### PR TITLE
update phase buttons

### PR DESCRIPTION
**Pull request by mercury233**
image
image
image
image

### CODE REVIEW

**Comment by edo9300** [comment]
Where is the shuffle button?

_Sent from my Nubia NX529J using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mercury233** [comment]
under the 3 chain buttons

**Comment by Yumekaki** [comment]
distinguishing mr3 and mr4 is ideal

**Comment by mercury233** [comment]
the DP button had become status indicator so it should be kept the same in MR3.

**Pull request merged**
