### PR TITLE
Update to add Online mode similar to percy

### PR DESCRIPTION
**Pull request by John-cos**

### CODE REVIEW

**Comment by John-cos** [comment]
Why was this closed?

**Comment by mercury233** [comment]
It don't make any sense. Please finish your code before make pull request.

**Comment by John-cos** [comment]
What it does is change the lan mode window so i basically functions like percys does. I modified it to get more data like name of duelists,type of duel etc etc.

**Comment by mercury233** [comment]
Sorry, it is **code** which should be in pull request, not idea.

**Comment by purerosefallen** [comment]
Why should we be similar to Percy? It really makes 0 sense.

**Comment by John-cos** [comment]
There is no reason it shouldn't be a standard feature.

**Pull request closed without merging**
