### PR TITLE
Sound

### PR DESCRIPTION
**Pull request by DailyShana**

### CODE REVIEW

**Comment by Zayelion** [comment]
1.) This works and covers use case, its the way its done in two of the variants.
2.) irrklang has some licencing issues with the principles of being open source. http://www.ambiera.com/irrklang/faq.html#opensource. If someone wants to use YGOPro commercially in the future (say Konami, or a group/company that has licenced YuGiOh properly), @Fluorohydride declared that they have to share the source for the gframe used. https://github.com/Fluorohydride/ygopro/blob/master/LICENSE ygopro-core is MIT so it doesnt have to be shared, https://github.com/Fluorohydride/ygopro-core/blob/master/LICENSE so server side systems are protected... so I dont know if these licences are comparable.
3.) I feel for principle's sake we need to find a difference sound engine and keep this commit for a record.

**Comment by IceYGO** [comment]
As I said in #1634, I do not like irrKlang since it is not using an open-source license.
I'm not against including it but only if we can also compile without it.

It's sad to see how few free audio libraries there are. :disappointed:
Maybe we could take a look at http://www.portaudio.com/, http://www.sfml-dev.org/ or https://www.openal.org/.

**Comment by Zayelion** [comment]
I prefer SFML, but @Fluorohydride why wasnt sound originally included?

**Comment by zh99998** [comment]
+1 for this request.

about licensing thing.
if someone (say Konami, or a group/company that has licensed YuGiOh properly), do you say Konami or company who can buy license from Konami, can't afford a audio library? this worry is stupid.

**Comment by fervi** [comment]
We can use music with 0AD. License is ok.
Ammon-Ra - fight
Honor_Bound - if winning
Taiko 1 / Taiko 2 - if losing

Victory Track - if win
Dried Tears - if lose

**Pull request closed without merging**
