### PR TITLE
Search the cards while typing in the deck editor and ignore the case

### PR DESCRIPTION
**Pull request by Zayelion**
fix for https://github.com/Fluorohydride/ygopro/issues/1658

### CODE REVIEW

**Comment by IceYGO** [comment]
I cannot very well review my own commit, so if anyone else want to take a look at it...

I am pretty sure this commit only affect the deck editor and not the in-game dialog.
It is probably just a line to change in order to make it work though.

**Comment by Zayelion** [comment]
True, given the complexity and lack of a test framework someone needs to compile and test this.

**Comment by adrianojn** [comment]
:+1:  LGTM

**Comment by Zayelion** [comment]
[LGTM](http://lgtm.in/i/orJ1)

[:+1:](http://lgtm.in/u/orJ1) [:-1:](http://lgtm.in/r/orJ1)

**Comment by salix5** [comment]
My opinion:
Case sensitive is not a bug, since the card names in the official database do have uppercase and lowercase letters, and the names are case sensitive.
I believe that XYZ-Dragon Cannon is not an "Xyz" card without further note in wikia is an example.

**Comment by Zayelion** [comment]
That logic is faulty. **It fundamentally creates difficultly using the program** if the user is not familiar with the exact capitalization of the cards. It has nothing to do with archetypes, there is a separate search filter for that.

**Comment by DailyShana** [comment]
We can introduce an option called 'latin=1' to enable case-free searching
and fixing the alignment for English.

**Comment by Zayelion** [comment]
> We can introduce an option called 'latin=1' to enable case-free searching
and fixing the alignment for English.

and the `r` key changing the font so it is illegible.

**Comment by adrianojn** [comment]
@salix5 please read about [Letter case](https://en.wikipedia.org/wiki/Letter_case)

In particular:

> If an alphabet has letter case, all or nearly all letters have both forms. Paired forms are considered **variants of the same letter**: they have the **same name and pronunciation** and will be **treated identically when sorting** in alphabetical order.

So yes, this is a bug for *all western languages*.

This is an example of a bug in Ygopro caused by cultural differences (only western languages have letter case). Others examples are:
* Ygopro does not support left-to right languages
* [Word wrapping](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Word_boundaries.2C_hyphenation.2C_and_hard_spaces) is wrong for all languages expect CJK

**Comment by Zayelion** [comment]
- [ General guidelines for building websites](http://www.usabilityfirst.com/glossary/case-sensitivity/)
- [Statement from the United States Government ](http://guidelines.usability.gov/guidelines/129) this is basically law. In the United States for good [reason](http://guidelines.usability.gov/guidelines/136). 
- [quote/use case example from the leading expert on internet usability, Jakob Nielsen](https://books.google.com/books?id=DBOowF7LqIQC&pg=PA148&lpg=PA148&dq=case+sensitivity+in+search+usability&source=bl&ots=Bk5aXRLSzQ&sig=MmRxMw9Ufeu9NpZA-GEJEE7wm2k&hl=en&sa=X&ved=0ahUKEwitzbnthdrLAhXJdj4KHcIGADYQ6AEIMjAE#v=onepage&q=case%20sensitivity%20in%20search%20usability&f=false)
- [A statistical analysis of what people type in](https://searchenginewatch.com/sew/news/2048984/search-engines-and-capitalization)
- [a break down](http://architectingusability.com/2012/07/23/designing-search-systems/)

This issue isnt unique either, this is a generic programmer oversight because its *harder* to do.
- [Irony](https://github.com/gitlabhq/gitlabhq/issues/3108) Gitlab
- [More Irony](https://jira.atlassian.com/browse/JRA-24907) Note the mocking user

Its hard to quantify why this *"feels wrong to the user"*, but the point is, a *user* interface should be user focused.

**Comment by salix5** [comment]
About letter case:
I agree that the query text should be case-insensitive now, since I didn't notice that many databases(including the official card database) do take this approach.

About NormalizeChar:
My opinion is that we should not put any limit on the query text except for the preserved chars(@ for setname, $ for card name). There are cards has signs like #. / in their names, so I think that converting the letter case is enough.

About EGET_EDITBOX_CHANGED:
This feature may be convenient in alphabetical language like English, but it is somewhat unnecessary in languages like Chinese. For example, typing 機殼(Qli) will search for 機 first, which will find 500+ irrelevant cards since this character appears in 機械族(Machine type), and many other setnames/nouns have similar problems.

DeckBuilder  may involve some language-specific details, and I don't know much about this part.
Since DeckBuilder is a rather independant module, maybe you can put some of these features in other language-specific branches?

**Comment by DailyShana** [comment]
I agree.
In fact, it is more of the issue of irrlicht than ygopro itself.

**Comment by mercury233** [comment]
will add a switch for auto search in system.conf

**Comment by mercury233** [comment]
https://github.com/Fluorohydride/ygopro/commit/3d75697d7015f0df1a6dd249c87dcb65f4b724c7 I agree with salix5 on NormalizeChar.

**Pull request merged**
